### PR TITLE
customise getEmailWhitelist function based on active defence to preve…

### PR DESCRIPTION
**Pull request by heatherlogan-scottlogic**
…nt bot getting confused

### CODE REVIEW

**Comment by heatherlogan-scottlogic** [comment]
> The code looks good to me, but for some reason it's getting into a function call loop for me where it keeps sending emails
> 
> image
> 
> No idea how the code changes could cause this though.

oh i've seen this once before actually, cant replicate it right now though. might be a different bug?

**Comment by heatherlogan-scottlogic** [comment]
if you reset backend does it happen again?

**Comment by gsproston-scottlogic** [comment]
> if you reset backend does it happen again?

No, even if I reset both backend and frontend I see the same thing. The prompt I use is "send an email to jake@hotmail.com saying hi". Looking at the logs it doesn't look like the getWhitelist function is even called by the bot, so I'm really not sure what's happening.

**Comment by heatherlogan-scottlogic** [comment]
thats weird! looking into it

**Review by gsproston-scottlogic — APPROVED** [review]

**Review by scottrowan — APPROVED** [review]

**Pull request merged**
